trigger:
- master

stages:
- stage: Linux
  jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - bash: |
          brew install ninja cmake
        displayName: 'Install Ninja and CMake and Clang 11'
      - bash: cmake -DCMAKE_TOOLCHAIN_FILE=$(Build.SourcesDirectory)/samples/CMakePresets/cmake/clang.cmake -DCMAKE_INSTALL_PREFIX=$(Build.SourcesDirectory)/CMakePresets/install/clang-linux -H$(Build.SourcesDirectory)/CMakePresets -B$(Build.SourcesDirectory)/CMakePresets/build/clang-linux -G "Ninja Multi-Config"
        displayName: 'CMakePresets Configure clang-linux'
      - bash: cmake --build $(Build.SourcesDirectory)/CMakePresets/build/clang-linux --config Debug
        displayName: 'CMakePresets Build Debug clang-linux'
      - bash: cmake --build $(Build.SourcesDirectory)/CMakePresets/build/clang-linux --config Release
        displayName: 'CMakePresets Build Release clang-linux'
- stage: Windows
  jobs:
  - job:
    pool:
      vmImage: 'windows-latest'
    strategy:
      matrix:
        AddressSanitizer Debug:
          MSBuildConfiguration: Debug
        AddressSanitizer Release:
          MSBuildConfiguration: Release
    steps:
      - task: MSBuild@1
        displayName: 'MSBuild AddressSanitizer'
        inputs:
          solution: 'AddressSanitizer/AddressSanitizer.sln'
          msbuildArchitecture: 'x64'
          configuration: '$(MSBuildConfiguration)'
  - job:
    pool:
      vmImage: 'windows-latest'
    strategy:
      matrix:
        Likely Debug:
          MSBuildConfiguration: Debug
        Likely Release:
          MSBuildConfiguration: Release
    steps:
      - task: MSBuild@1
        displayName: 'MSBuild Likely'
        inputs:
          solution: 'Likely/Likely.sln'
          msbuildArchitecture: 'x64'
          configuration: '$(MSBuildConfiguration)'